# Generated by Django 6.0.6 on 2026-06-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parts_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('invoice_date', models.DateField()),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='services.servicerecord')),
            ],
        ),
    ]
