# Generated by Django 6.0.6 on 2026-06-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('technicians', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='technicians.technician')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='inventory.sparepart')),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='services.servicerecord')),
            ],
        ),
    ]
