# Generated by Django 6.0.6 on 2026-06-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('general', 'General Maintenance'), ('oil_change', 'Oil & Filter Change'), ('brakes', 'Brake Repair & Service'), ('engine', 'Engine Diagnostics & Tuning'), ('alignment', 'Wheel Alignment & Balancing'), ('ac', 'Air Conditioning Service'), ('electrical', 'Electrical Diagnostics'), ('bodywork', 'Body Repair & Detailing')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vehicles.vehicle')),
            ],
        ),
    ]
