# Generated by Django 6.0.6 on 2026-06-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('technician', 'Technician'), ('service_advisor', 'Service Advisor')], default='customer', max_length=20),
        ),
    ]
