# Generated by Django 6.0.6 on 2026-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity available')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
